### ISSUE TITLE
1) Database has at least 3 tables with 40 records (10 points)

### ISSUE THREAD

**Issue by WillHutt** [IceCube1333/cst336Team-Project-Description#1]

**Comment by adiesh** [comment]
Created 3 tables under the "heroku_860455424cb7b6b" database (electronics, apparel, and customers). Let me know if I need to modify them in any way.

**Comment by WillHutt** [comment]
I don't think we'll need users as we won't have anybody logging in. Maybe we should change it to a different shopping item. I believe we mentioned anime or something.

**Comment by WillHutt** [comment]
Also I know you sent the cloud9 invite but for some reason I never got it in my email. Could you send it again please?

**Comment by adiesh** [comment]
Sure. I will go ahead and send it again. I will change the users table to anime

**Comment by adiesh** [comment]
I just shared my workspace again.

**Comment by adiesh** [comment]
Now officially have 3 tables (electronics, apparel, and anime).  Have a total of 44 records

**Comment by adiesh** [comment]
Just pushed the database connection file (information.php) to github. I can go ahead and look into the css or anything else. If you can give me any feedback regarding the database, that would be great.

**Comment by WillHutt** [comment]
Awesome! I'm cleaning up the index.php to make it simpler to cut down on any extra work that is not necessary to the things required.

**Comment by WillHutt** [comment]
I'll be pushing it soon. Also in the future please make a branch for your work and save master for the final push. That way we won't accidentally over write what people are working on.
