### ISSUE TITLE
3) Users can sort results (asc,desc) using at least one field (10 points)

### ISSUE THREAD

**Issue by WillHutt** [IceCube1333/cst336Team-Project-Description#3]

**Comment by sgrether** [comment]
This is finished, although because of the design of the site, it only sorts the individual product types, it doesn't sort all of them together.

**Comment by adiesh** [comment]
I don't know if this is an issue, but should I create another table called "company"? Company will have a an companyID and companyName. If I add another column called companyID to each table, then it should have more of a relationship. What do you guys think?

**Comment by sgrether** [comment]
I'm trying to get a hold of John, the TA, to see if it's necessary. Until then I think it's fine if we leave it the way it is

**Comment by adiesh** [comment]
For sure. Let me know if John gets back to you.

**Comment by WillHutt** [comment]
Probably not something we need to do at least imo since it doesn’t call for anything like that. Let me know what happens. I don’t care either way as long as we get it done and it works properly.

I’m gonna be working on different hw and studying for midterms for other classes. I’ll make sure to finish my part before tomorrow at midnight since it’s due on 11/14 at 11:55pm

- Will

**Comment by sgrether** [comment]
John said it's not an issue, so we don't need to change it. You should try and finish your parts early tho since we still need to do css stuff as well as the word doc.

**Comment by adiesh** [comment]
I can look into the css and start a google doc.
